common:
  java_version: 8u201
  java_home: "/usr/java/jdk1.8.0_201-amd64"
  java_download: "http://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.rpm"
  java_jce_download: "http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip"

