- name: remove old install dir
  file: path= "{{ install_dir }}" state=absent

- name: create install dir
  file: path="{{ install_dir }}" state=directory

- name: remove old temporary install dir
  file: path="{{ install_temp_dir }}" state=absent

- name: create temporary install dir
  file: path="{{ install_temp_dir }}" state=directory

- import_tasks: java.yml
  when: "install_java == True"

  #- import_tasks: mirror.yml

- import_tasks: scala.yml

